apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: 192.168.33.10
      user: vagrant
      port: 22
      keyPath: null
    role: controller
    privateInterface: eth1 
  # - ssh:
  #     address: 192.168.33.11
  #     user: vagrant
  #     port: 22
  #     keyPath: null
  #   role: controller
  #   privateInterface: eth1 
  - ssh:
      address: 192.168.33.12
      user: vagrant
      port: 22
      keyPath: null
    role: worker
    privateInterface: eth1 
  - ssh:
      address: 192.168.33.13
      user: vagrant
      port: 22
      keyPath: null
    role: worker
    privateInterface: eth1 
  # - ssh:
  #     address: 192.168.33.14
  #     user: vagrant
  #     port: 22
  #     keyPath: null
  #   role: worker
  #   privateInterface: eth1 
  k0s:
    version: v1.28.4+k0s.0
    dynamicConfig: false
    config: 
      spec:
        extensions:
          storage:
            type: openebs_local_storage
          helm:
            repositories:
            - name: mirantis
              url: https://charts.mirantis.com
            - name: metallb
              url: https://charts.bitnami.com/bitnami
            - name: stable
              url: https://charts.helm.sh/stable
            charts:
            - name: nginx
              chartname: mirantis/nginx
              namespace: nginx
              version: 0.1.0
            - name: metallb
              chartname: bitnami/metallb
              namespace: metallb
              version: 4.8.0
              values: |2
                configInline:
                  address-pools:
                  - name: generic-cluster-pool
                    protocol: layer2
                    addresses:
                    - 192.168.33.100-192.168.33.200

              


